#!/bin/bash

SUPPORTED_ARCHITECTURES=(armeabi armeabi-v7a mipsel x86)
ANDROID_NDK_ROOT_PATH=~/ndkdir
ANDROID_API_VERSION=9
NDK_TOOLCHAIN_ABI_VERSION=4.8

NUMBER_OF_CORES=$(nproc)
HOST_UNAME=$(uname -m)
